name: Docker Image CI

on:
  push:
    branches: [ "master" ]  # master 브랜치에 푸시될 때 실행
  pull_request:
    branches: [ "master" ]  # master 브랜치로 PR을 생성할 때 실행
  workflow_dispatch:  # 수동 트리거 시에도 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # `uses`를 통해 `actions/checkout` 액션을 사용해야 함

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build ./backend --tag bento3/backend:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push bento3/backend:${{ github.sha }}
