name: Docker Image CI

on:
  push:
    branches: [ "master" ]  # master 브랜치에 푸시될 때 실행
  pull_request:
    branches: [ "master" ]  # master 브랜치로 PR을 생성할 때 실행
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'  # 기본적으로 master 브랜치를 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}  # 사용자가 입력한 브랜치를 사용

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image for ARM architecture
      run: |
        docker buildx build ./backend --platform linux/arm64 -t bento3/backend:latest --push
      # ./backend 디렉토리에서 ARM64 이미지 빌드 및 푸시

